 var multiApp = angular.module('new', []);

// create a controller
 multiApp.controller('dCtrl', ['$scope', '$controller', function ($scope, $controller) {
     $scope.movies =
        [{"Title":"Kill Bill","Year":"2003","Released":"10 Oct 2003","Runtime":"111 min","Genre":"Action","Director":"Quentin Tarantino","Actors":"Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah","Plot":"The Bride wakens from a four-year coma. The child she carried in her womb is gone. Now she must wreak vengeance on the team of assassins who betrayed her - a team she was once part of.","Language":"English, French, Japanese","Poster":"http://ia.media-imdb.com/images/M/MV5BMTU1NDg1Mzg4M15BMl5BanBnXkFtZTYwMDExOTc3._V1_SX300.jpg","imdbRating":"8.1","imdbVotes":"716,343","imdbID":"tt0266697"},
  		{"Title":"Ice","Year":"1998","Released":"22 Jul 2000","Runtime":"93 min","Genre":"Adventure","Director":"Jean de Segonzac","Actors":"Grant Show, Udo Kier, Eva LaRue, Flex Alexander","Plot":"After the whole North of the Equator freezes below zero, a group of people in Los Angeles risk their lives while trying to \"escape\" from the city's hostile conditions, in order to take a ship to a hotter place on Earth.","Language":"English","Poster":"http://ia.media-imdb.com/images/M/MV5BZTk2MTA4YmYtYjY0ZC00YmIwLWE0YjYtNDI2NDBhYmNkYmI2XkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg","imdbRating":"5.0","imdbVotes":"885","imdbID":"tt0160393"},
  		{"Title":"Nacho Libre","Year":"2006","Released":"16 Jun 2006","Runtime":"92 min","Genre":"Comedy","Director":"Jared Hess","Actors":"Jack Black, Ana de la Reguera, Héctor Jiménez, Darius Rose","Plot":"Berated all his life by those around him, a monk follows his dream and dons a mask to moonlight as a Luchador (Mexican wrestler).","Language":"English, Spanish","Poster":"http://ia.media-imdb.com/images/M/MV5BMjE1OTQxNTk4NV5BMl5BanBnXkFtZTcwNDQzMjYzMQ@@._V1_SX300.jpg","imdbRating":"5.7","imdbVotes":"64,580","imdbID":"tt0457510"},
  		{"Title":"Van Helsing","Year":"2004","Released":"07 May 2004","Runtime":"131 min","Genre":"Action","Director":"Stephen Sommers","Actors":"Hugh Jackman, Kate Beckinsale, Richard Roxburgh, David Wenham","Plot":"The notorious monster hunter is sent to Transylvania to stop Count Dracula who is using Dr. Frankenstein's research and a werewolf for some sinister purpose.","Language":"English, Latin","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY0NjcyOTUxNV5BMl5BanBnXkFtZTYwNjMxNjc2._V1_SX300.jpg","imdbRating":"6.0","imdbVotes":"191,868","imdbID":"tt0338526"},
  		{"Title":"Blair Witch","Year":"1999","Rated":"R","Released":"30 Jul 1999","Runtime":"81 min","Genre":"Horror","Director":"Daniel Myrick, Eduardo Sánchez","Writer":"Daniel Myrick, Eduardo Sánchez","Actors":"Heather Donahue, Joshua Leonard, Michael C. Williams, Bob Griffin","Plot":"Three film students vanish after traveling into a Maryland forest to film a documentary on the local Blair Witch legend, leaving only their footage behind.","Language":"English","Country":"USA","Awards":"15 wins & 21 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTg0NjMyNTY4OF5BMl5BanBnXkFtZTYwOTMxOTY4._V1_SX300.jpg","Metascore":"81","imdbRating":"6.4","imdbVotes":"182,793","imdbID":"tt0185937","Type":"movie","Response":"True"},
  		{"Title":"Cars","Year":"2006","Rated":"G","Released":"09 Jun 2006","Runtime":"117 min","Genre":"Adventure","Director":"John Lasseter, Joe Ranft","Writer":"John Lasseter (original story by), Joe Ranft (original story by), Jorgen Klubien (original story by), Dan Fogelman (screenplay), John Lasseter (screenplay), Joe Ranft (screenplay), Kiel Murray (screenplay), Phil Lorin (screenplay), Jorgen Klubien (screenplay)","Actors":"Owen Wilson, Paul Newman, Bonnie Hunt, Larry the Cable Guy","Plot":"A hot-shot race-car named Lightning McQueen gets waylaid in Radiator Springs, where he finds the true meaning of friendship and family.","Language":"Yiddish, English, Italian, Japanese","Country":"USA","Awards":"Nominated for 2 Oscars. Another 27 wins & 28 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_SX300.jpg","Metascore":"73","imdbRating":"7.2","imdbVotes":"255,792","imdbID":"tt0317219","Type":"movie","Response":"True"},
  		{"Title":"Cops","Year":"1922","Rated":"UNRATED","Released":"01 Mar 1922","Runtime":"18 min","Genre":"Comedy","Director":"Edward F. Cline, Buster Keaton","Writer":"Buster Keaton, Edward F. Cline","Actors":"Buster Keaton","Plot":"A series of mishaps manages to make a young man get chased by a big city's entire police force.","Language":"English","Country":"USA","Awards":"1 win.","Poster":"http://ia.media-imdb.com/images/M/MV5BYjI5NDM2NmUtMDNlOS00ZjRkLWE5MmMtNThmMzIzNzBiM2Y0XkEyXkFqcGdeQXVyMjExNjgyMTc@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.8","imdbVotes":"3,994","imdbID":"tt0013025","Type":"movie","Response":"True"},
  		{"Title":"Caperucita roja","Year":"1960","Rated":"N/A","Released":"05 May 1960","Runtime":"85 min","Genre":"Drama","Director":"Roberto Rodríguez","Writer":"Fernando Morales Ortiz (story), Ricardo Garibay (special collaboration), Charles Perrault (story), Fernando Morales Ortiz (adaptation), Rafael García Travesi (adaptation)","Actors":"María Gracia, Manuel 'Loco' Valdés, Santanón, Prudencia Grifell","Plot":"The classic story of the Red Riding Hood spiced up by a couple of funny characters like the dog Duke, companion to the girl in her adventures, and the stinky Skunk, henchman to the Wolf.","Language":"Spanish","Country":"Mexico","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAzNzA1MTA1NF5BMl5BanBnXkFtZTgwMDU4Nzk1MDE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.4","imdbVotes":"68","imdbID":"tt0053693","Type":"movie","Response":"True"},
  		{"Title":"The Simpsons","Year":"1989–","Rated":"TV-14","Released":"17 Dec 1989","Runtime":"22 min","Genre":"Comedy","Director":"N/A","Writer":"James L. Brooks, Matt Groening, Sam Simon","Actors":"Dan Castellaneta, Julie Kavner, Nancy Cartwright, Yeardley Smith","Plot":"The satiric adventures of a working-class family in the misfit city of Springfield.","Language":"English, Spanish, Albanian, French, Japanese, German, Russian, Hindi, Swahili, Italian, Swedish, Turkish, Cantonese, Mandarin, Hebrew, Arabic, Klingon, Bengali, Czech","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 155 wins & 258 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk0MTAzMzgxOV5BMl5BanBnXkFtZTgwOTM3Mjg4MzE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.8","imdbVotes":"256,334","imdbID":"tt0096697","Type":"series","Response":"True"},
  		{"Title":"Face","Year":"1997","Rated":"R","Released":"26 Sep 1997","Runtime":"105 min","Genre":"Crime","Director":"Antonia Bird","Writer":"Ronan Bennett (screenplay)","Actors":"Robert Carlyle, Ray Winstone, Steve Sweeney, Gerry Conlon","Plot":"Ray is an aging ex-socialist who has become a bankrobber after seeing the demise of socialism in 1980s Britain. Teaming up with a gang of other has-beenish crims, he commits one bank job ...","Language":"English","Country":"UK","Awards":"4 wins.","Poster":"http://ia.media-imdb.com/images/M/MV5BNTAyNTgxNDc0MF5BMl5BanBnXkFtZTcwMDYxMjA0MQ@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.8","imdbVotes":"3,529","imdbID":"tt0119092","Type":"movie","Response":"True"},
  		{"Title":"The Note","Year":"2007","Rated":"N/A","Released":"08 Dec 2007","Runtime":"88 min","Genre":"Family","Director":"Douglas Barr","Writer":"Paul W. Cooper (teleplay), Angela Hunt (novel)","Actors":"Genie Francis, Ted McGinley, Rick Roberts, Genelle Williams","Plot":"After a tragic plane crash, a local journalist discovers a note that she believes was written by one of the passengers. She seeks the note's intended receiver, but the journey is more revealing of her own past.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA4NDkxOTEzNl5BMl5BanBnXkFtZTcwMzUyNzU3Mg@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.9","imdbVotes":"486","imdbID":"tt1146321","Type":"movie","Response":"True"},
  		{"Title":"Madagascar","Year":"2005","Rated":"PG","Released":"27 May 2005","Runtime":"86 min","Genre":"Adventure","Director":"Eric Darnell, Tom McGrath","Writer":"Mark Burton, Billy Frolick, Eric Darnell, Tom McGrath","Actors":"Ben Stiller, Chris Rock, David Schwimmer, Jada Pinkett Smith","Plot":"Spoiled by their upbringing with no idea what wild life is really like, four animals from New York Central Zoo escape, unwittingly assisted by four absconding penguins, and find themselves in Madagascar, among a bunch of merry lemurs","Language":"English, German, Portuguese, French, Spanish","Country":"USA","Awards":"4 wins & 29 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY4NDUwMzQxMF5BMl5BanBnXkFtZTcwMDgwNjgyMQ@@._V1_SX300.jpg","Metascore":"57","imdbRating":"6.9","imdbVotes":"258,308","imdbID":"tt0351283","Type":"movie","Response":"True"},
  		];
}]);

// create another controller
 multiApp.controller('eCtrl', ['$scope', '$controller', function ($scope, $controller) {
     $scope.text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi lorem egestas odio, vitae scelerisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Mauris ante ligula, facilisis sed ornare eu, lobortis in odio. Praesent convallis urna a lacus interdum ut hendrerit risus congue. Nunc sagittis dictum nisi, sed ullamcorper ipsum dignissim ac.';
 }]);

